//ERRORS 
export const GET_ERRORS = "GET_ERRORS";

// ARTIST
export const ARTIST_LOADING = "ARTIST_LOADING";
export const SET_CURRENT_ARTIST = "SET_CURRENT_ARTIST";
export const EDIT_ARTIST = "EDIT_ARTIST";
export const GET_ARTISTS = "GET_ARTISTS";
export const FETCH_ARTISTS = "FETCH_ARTISTS"